Correctly handle array of routes for a method
Was previously failing as follows because an array
has no "callbacks" property.

oauth2-server/lib/oauth2server.js:217
  app.routes[method].callbacks.forEach(lockdownExpress3);
                                 ^
TypeError: Cannot call method 'forEach' of undefined
  at OAuth2Server.lockdown (oauth2-server/lib/oauth2server.js:217:36)